"""Export verified residual-floor results into the ACE manuscript (no refitting).

Called by the paper build. Requires the completed residual_floor_pipeline.py
outputs; preserves that analysis manifest and its source/results archive.
"""
from pathlib import Path
import hashlib
import json
import shutil
import re
import zipfile
from residual_floor_common import SILICA_UM

ROOT=Path(__file__).resolve().parents[2]
DATA=ROOT/'data/ace_floor/w0p25'
PAPER=ROOT/'outputs/ace_manuscript_tables'   # ACE side-study tables (not part of paper 1)

def digest(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def read(name):return json.loads((DATA/name).read_text())
def fmt(x):return '---' if x is None else f'{1000*x:.2f}'
def ci_text(c):return '---' if c['lower'] is None else f"$[{fmt(c['lower'])}, {fmt(c['upper'])}]$"
def table(name,caption,label,columns,header,rows):
    body='\n'.join(' & '.join(r)+r' \\' for r in rows)
    s=(r'\begin{table}[t]'+'\n'+r'\color{ClaudeGreen}'+'\n'+
       r'\caption{\ClaudeText{'+caption+'}}\n'+r'\label{'+label+'}\n'+
       r'\centering\small'+'\n'+r'\begin{tabular}{'+columns+'}\n'+r'\toprule'+'\n'+
       ' & '.join(header)+r' \\'+'\n'+r'\midrule'+'\n'+body+'\n'+
       r'\bottomrule'+'\n'+r'\end{tabular}'+'\n'+r'\end{table}'+'\n')
    (PAPER/'tables'/name).write_text('% Generated by residual_floor_manuscript.py; edit the exporter, not this file.\n'+s)

def zip_entry(archive,name,data):
    entry=zipfile.ZipInfo(name,date_time=(2026,9,9,0,0,0))
    entry.compress_type=zipfile.ZIP_DEFLATED
    entry.external_attr=0o644 << 16
    archive.writestr(entry,data)

def package():
    exporter=Path(__file__).resolve();name=str(exporter.relative_to(ROOT))
    with zipfile.ZipFile(DATA/'residual_floor_code.zip') as source, zipfile.ZipFile(PAPER/'ace_residual_floor_code.zip','w') as target:
        for member in source.namelist():
            if member != name:zip_entry(target,member,source.read(member))
        zip_entry(target,name,exporter.read_bytes())
        zip_entry(target,'paper_export_manifest.json',(PAPER/'residual_floor_export.json').read_bytes())
        zip_entry(target,'MANUSCRIPT_EXPORT.txt',b'The original analysis manifest is preserved. The separate paper export manifest hashes the exporter and generated tables/figures. In the SAGE repository, run the residual-floor pipeline with separately obtained ACE inputs, then run residual_floor_manuscript.py or the ACE paper build.sh. The exporter uses the archived summaries and does not refit spectra. Raw spectra are not redistributed. This is a local repository-dependent snapshot, not a public code deposit.\n')
    files={PAPER/'main.tex',PAPER/'supplement.tex',PAPER/'references.bib',PAPER/'residual_floor_export.json'}
    for pattern in ['*.cls','*.cfg','*.bst','*.sty','sections/*.tex','tables/residual_*.tex']:
        files.update(PAPER.glob(pattern))
    for path in list(files):
        if path.suffix!='.tex':continue
        active='\n'.join(l for l in path.read_text().splitlines() if not l.lstrip().startswith('%'))
        for figure in re.findall(r'\\includegraphics(?:\[[^\]]*\])?\{([^}]+)\}',active):files.add(PAPER/figure)
    with zipfile.ZipFile(PAPER/'overleaf_update.zip','w') as archive:
        for path in sorted(files):zip_entry(archive,str(path.relative_to(PAPER)),path.read_bytes())
        zip_entry(archive,'UPLOAD_README.txt',b'Upload this source bundle. Compile main.tex for the paper and supplement.tex for the supplement using pdfLaTeX. Generated tables and figures are included; Overleaf does not need to execute Python. No source-file deletions are required. Review changes are green. Code/results archives are separate and are not needed for TeX compilation.\n')
    for path in [PAPER/'overleaf_update.zip',PAPER/'ace_residual_floor_code.zip']:
        with zipfile.ZipFile(path) as archive:
            if archive.testzip() is not None:raise ValueError('Corrupt archive: '+str(path))


def main():
    manifest=read('manifest.json')
    # Reject stale/hand-edited source summaries or figures, independently of
    # any subsequent changes to analysis code. The original manifest is kept.
    for name,expected in manifest['outputs'].items():
        if digest(DATA/name)!=expected:raise ValueError('Result hash mismatch: '+name)
    (PAPER/'tables').mkdir(exist_ok=True)
    atlas=read('atlas.json');core={r['center_um']:r for r in atlas['19_22']}
    materials=[('Dolomite',6.4),('Calcite',6.9),('Silica',SILICA_UM),('Dolomite',11.3),('Calcite',11.4),('Alumina',12.9)]
    rows=[]
    for material,c in materials:
        r=core[c];ci=r['sd_bootstrap_95']
        rows.append([material,f'{c:g}',str(r['n']),fmt(r['sd']),
                     ci_text(ci)])
    table('residual_materials.tex',r'Full 0.25-$\mu$m elements at 19--22\,km, using one native tangent spectrum per occultation and complete calendar-year holdout. SD and intervals are in $10^{-3}$ residual-ratio OD. The five evaluable bands retain all 143 occultations and all 500 bootstrap draws. A dash denotes insufficient complete predictions, not a zero floor.','tab:floors','llrrr',
          ['Motivating material',r'Center ($\mu$m)','$n$','SD',r'95\,\% interval'],rows)
    rows=[]
    for _,c in materials:
        cells=[]
        for altitude in ['16_19','19_22','22_25']:
            r=next(r for r in atlas[altitude] if r['center_um']==c)
            cells.append('---' if r['status']!='estimated' else f"{fmt(r['sd'])} ({r['n']})")
        rows.append([f'{c:g}',*cells])
    table('residual_altitude.tex',r'Full-element prediction SD in $10^{-3}$ OD, with the number of complete predictions in parentheses. Each altitude interval selects its own nearest native tangent spectrum. The available samples contain 115, 143, and 142 occultations, respectively. Missing elements are not replaced by quiet subsets.','tab:floor_altitude','rrrr',
          [r'Center ($\mu$m)','16--19 km','19--22 km','22--25 km'],rows)
    sens=read('sensitivity.json');delta=read('paired_sd_reductions.json');rows=[]
    for _,c in materials:
        d=delta[f'{c:g}_rank3']
        vals=[fmt(core[c]['sd'])]+[fmt(sens[f'sensitivity_{c:g}um_{m}']['sd']) for m in ['rank3','rank5','availability_mask']]
        ci=ci_text(d)
        rows.append([f'{c:g}',*vals,ci])
    table('residual_models.tex',r'Prediction SD in $10^{-3}$ OD at 19--22\,km. Three- and five-mode fits share the two-mode training mask. The availability-only alternative drops the intercept cut. The last column is the paired year-bootstrap interval for two-mode minus three-mode SD; every evaluable interval includes zero.','tab:floor_models','rrrrrr',
          [r'Center ($\mu$m)','Two modes','Three modes','Five modes','No $A$ cut',r'$\Delta$ interval'],rows)
    r=core[SILICA_UM];rows=[]
    names={'standard':'Full proxies','cross_year':'Different years','same_year':'Same year','same_direction':'Same sunrise/sunset',
           'height_025':r'$|\Delta h|\le0.25$ km','latitude_5':r'$|\Delta\phi|\le5^\circ$',
           'split_blue':'Blue halves','split_red':'Red halves','weak_windows':'Weak windows'}
    for k,v in r['matched_pairs'].items():
        q=v['30'];ci=q['rms_bootstrap_95']
        rows.append([names[k],fmt(q['rms']),f"{q['max_proxy_distance']:.3f}",ci_text(ci)])
    table('residual_pairs.tex',r'Matching sensitivity at '+f'{SILICA_UM:g}'+r'$\um$ and 19--22\,km for the first 30 disjoint pairs. Pair RMS is $\mathrm{RMS}(\Delta q/\sqrt{2})$, in $10^{-3}$ OD. Intervals are descriptive 2.5--97.5 bootstrap percentiles from rematching; nominal statistical coverage is not established. Distances are standardized within each choice of proxies and are not interchangeable between choices.','tab:floor_pairs','lrrr',
          ['Matching rule','Pair RMS','Maximum distance','Resampling interval'],rows)
    rows=[]
    for c in [6.4,6.9,SILICA_UM,11.3,11.4,12.9]:
        for alt in ['16_19','19_22','22_25']:
            q=next(x for x in atlas[alt] if x['center_um']==c);ci=q['sd_bootstrap_95']
            rows.append([f'{c:g}',alt.replace('_','--'),str(ci['valid_draws']),
                         ci_text(ci)])
    table('residual_intervals.tex',r'Bootstrap support for full-element SD. Intervals are in $10^{-3}$ OD and use successful draws only, out of 500 attempted. Failures reflect the prescribed coverage and fitting requirements; their omission makes the interval conditional on successful prediction.','tab:floor_intervals','rrrr',
          [r'Center ($\mu$m)','Height (km)','Valid draws',r'95\,\% interval'],rows)
    for name in ['floor_atlas.png','averaging_and_matching.png']:
        shutil.copyfile(DATA/name,PAPER/'figures'/name)
    files=sorted((PAPER/'tables').glob('residual_*.tex'))+[PAPER/'figures'/n for n in ['floor_atlas.png','averaging_and_matching.png']]
    record={'analysis_manifest_sha256':digest(DATA/'manifest.json'),'exporter_sha256':digest(Path(__file__)),
            'generated_files':{str(p.relative_to(PAPER)):digest(p) for p in files}}
    (PAPER/'residual_floor_export.json').write_text(json.dumps(record,indent=2)+'\n')
    package()
    print('Exported five verified tables, two figures, and source/code archives to the ACE paper.')

if __name__=='__main__':main()
