"""Regenerate the Paper 1 tables that are pure transcriptions of archived JSON
results (round 53, referee RC1 re-run on the edge-grid gain, the design-budget
floor anchor and the element grid centred on 8.80 um):

  tables/element_width_scan.tex   <- outputs/resolution_sensitivity_calibrated.json
                                      + outputs/ace_v52/nulltest_resolution.json
  tables/nulltest_conventions.tex <- outputs/ace_v52/nulltest_convention.json

Numbers therefore trace to the archives by construction.  The tables are
written plain; --mark wraps the changed text in the paper's review markup.
"""
from __future__ import annotations
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PAPER = ROOT   # tables/ of this repository


def f3(x):
    return f"{x:.3f}" if x < 0.1 else f"{x:.2f}"


def f3w(x):
    """three decimals, as the element-width table has always been quoted"""
    return f"{x:.3f}"


def element_width_table(mark):
    R = json.load(open(ROOT / "outputs/resolution_sensitivity_calibrated.json"))
    N = json.load(open(ROOT / "outputs/ace_v52/nulltest_resolution.json"))
    rows = []
    for dl in ["0.05", "0.08", "0.1", "0.15", "0.2", "0.25", "0.3"]:
        cells = [f"${float(dl):g}$"]
        for rng in ("band", "window"):
            r = R["results"][rng][dl]
            a = N["ranges"][rng][dl]
            ace = "---"
            if a.get("usable", True) and a.get("mmin_emp_shell") is not None and a["mmin_emp_shell"] < 5:
                lo, hi = a["mmin_emp_shell_range"]
                ace = f"${a['mmin_emp_shell']:.2f}$ [{lo:.2f}--{hi:.2f}]"
            cells += [str(r["n_elements"]), f"${f3w(r['mmin'])}$", f"${f3w(r['mmin_corr']['0.25'])}$", ace]
        rows.append(" & ".join(cells) + r" \\")
    b0 = R["results"]["band"]["0.1"]["mmin_phase0"]
    w0 = R["results"]["window"]["0.1"]["mmin_phase0"]
    wrap = (lambda s: r"\ClaudeText{" + s + "}") if mark else (lambda s: s)
    cap = (r"Single-sounding threshold $M_{\min}^{(3\sigma)}$ [Tg] against the spectral element width $\Delta\lambda$, "
           r"for the $8$--$13~\mu$m band and the $7.8$--$9.3~\mu$m window (heritage triplet, seven background parameters free): "
           r"number of elements $N$, the linearized threshold with independent per-element floors and with floors correlated over "
           r"$\ell=0.25~\mu$m (medians over five placements of the element grid), and the ACE null test (median and range over the "
           r"same five placements, per-shell convention). Dashes: the window cannot support the seven-parameter fit. "
           + wrap(r"Grid placement 0 of the scan is the design grid centred on $8.80~\mu$m, for which the $0.1$-$\mu$m row gives "
                  + f"${b0:.3f}$ and ${w0:.3f}$~Tg, the baselines of Table~\\ref{{tab:robust_summary}} to $1\\,\\%$ "
                  + r"(fine-grid box averaging of the Mie columns here against the design's per-element quadrature); "
                  + r"the medians over the placements are quoted in the table."))
    tex = (r"""% Generated by reproduce/paper1_tables_round53.py from outputs/resolution_sensitivity_calibrated.json and outputs/ace_v52/nulltest_resolution.json (round 53).
\begin{table*}[t]
\caption{""" + cap + r"""}
\label{tab:element_width}
\centering
\small
\begin{adjustbox}{max width=\textwidth}
\begin{tabular}{c ccc c ccc c}
\toprule
& \multicolumn{4}{c}{band $8$--$13~\mu$m} & \multicolumn{4}{c}{window $7.8$--$9.3~\mu$m} \\
\cmidrule(lr){2-5}\cmidrule(lr){6-9}
$\Delta\lambda$ [$\mu$m] & $N$ & indep. & $\ell=0.25$ & ACE [range] & $N$ & indep. & $\ell=0.25$ & ACE [range] \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{adjustbox}
\end{table*}
""")
    (PAPER / "tables/element_width_scan.tex").write_text(tex)
    print("wrote tables/element_width_scan.tex")


def conventions_table(mark):
    d = json.load(open(ROOT / "outputs/ace_v52/nulltest_convention.json"))
    n = d["nulltest_cross_convention"]; g = d["design_cross_convention"]
    rho = d["rho"]
    rows = [
        (r"Full $8$--$13~\mu$m spectrum, native $2$~cm$^{-1}$ (empirical / formal)",
         f3(n['full']['mmin_emp_slant']) + " / " + f3(n['full']['mmin_formal_slant']),
         f3(n['full']['mmin_emp_shell']) + " / " + f3(n['full']['mmin_formal_shell'])),
        (r"Window $7.8$--$9.3~\mu$m, native $2$~cm$^{-1}$ (empirical / formal)",
         f3(n['win2']['mmin_emp_slant']) + " / " + f3(n['win2']['mmin_formal_slant']),
         f3(n['win2']['mmin_emp_shell']) + " / " + f3(n['win2']['mmin_formal_shell'])),
        (r"Window, fifteen $0.1$-$\mu$m elements (empirical / formal)",
         f3(n['win01']['mmin_emp_slant']) + " / " + f3(n['win01']['mmin_formal_slant']),
         f3(n['win01']['mmin_emp_shell']) + " / " + f3(n['win01']['mmin_formal_shell'])),
    ]
    for key, label in [("band 8-13 @0.1 | band01 alone", r"Linearized: $8$--$13~\mu$m band alone at $0.1~\mu$m, seven parameters"),
                       ("window alone | full 7-param", r"Linearized: window alone, seven parameters"),
                       ("band 8-13 @0.1 | triplet + band01", r"Linearized: heritage triplet plus $8$--$13~\mu$m band (the design)"),
                       ("heritage triplet (448,756,1544) | full 7-param", r"Linearized: heritage triplet plus window subset")]:
        rows.append((label, f3(g[key]['mmin_slant']), f3(g[key]['mmin_shell'])))
    wrap = (lambda s: r"\ClaudeText{" + s + "}") if mark else (lambda s: s)
    cap = wrap(r"The ACE-FTS null tests and the linearized thresholds side by side, in both conventions: $M_{\min}^{(3\sigma)}$ [Tg] "
               r"for the slant fit at the median $20.5$-km tangent (the convention of the fits of Sect.~\ref{sec:scisat_nulltest}) and per "
               r"$0.5$-km retrieved shell (the convention of the design, Sect.~\ref{sec:solution_threshold}); the two differ by "
               + f"$\\rho={rho:.2f}$. "
               + r"Empirical: $3\times$ the robust scatter of the fitted masses across the $101$ occultations; formal: $3\times$ the median "
               r"propagated error, with the design's per-element floors as weights. The linearized rows are the Fisher thresholds of the "
               r"design analysis with the same floors, stated in the same two conventions.")
    tex = (r"""% Generated by reproduce/paper1_tables_round53.py from outputs/ace_v52/nulltest_convention.json (ace_nulltest_convention.py), round 53.
\begin{table*}[t]
\caption{""" + cap + r"""}
\label{tab:nulltest_conventions}
\centering
\small
\begin{tabular}{p{9.5cm}cc}
\toprule
 & slant, $20.5$-km tangent [Tg] & per $0.5$-km shell [Tg] \\
\midrule
""" + "\n".join(f"{a} & {b} & {c} \\\\" for a, b, c in rows) + r"""
\bottomrule
\end{tabular}
\end{table*}
""")
    (PAPER / "tables/nulltest_conventions.tex").write_text(tex)
    print("wrote tables/nulltest_conventions.tex")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--mark", action="store_true", help="wrap the changed text in the paper's review markup (\\ClaudeText)")
    ap.add_argument("--only", nargs="*", choices=["width", "conventions"])
    a = ap.parse_args()
    which = a.only or ["width", "conventions"]
    if "width" in which:
        element_width_table(a.mark)
    if "conventions" in which:
        conventions_table(a.mark)
